import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TurnkeyProvider } from "@turnkey/sdk-react";
import "@turnkey/sdk-react/styles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const config = {
  apiBaseUrl: "https://api.turnkey.com",
  defaultOrganizationId: process.env
    .NEXT_PUBLIC_TURNKEY_ORGANIZATION_ID as string
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TurnkeyProvider config={config}>{children}</TurnkeyProvider>
      </body>
    </html>
  );
}
